#+title: satysfi-mode.el
#+author: Naoya Yamashita

[[https://github.com/conao3/satysfi-mode.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/satysfi-mode.el.svg?style=flat-square]]
[[https://github.com/conao3/satysfi-mode.el/releases][https://img.shields.io/github/tag/conao3/satysfi-mode.el.svg?style=flat-square]]
[[https://github.com/conao3/satysfi-mode.el/actions][https://github.com/conao3/satysfi-mode.el/workflows/Main%20workflow/badge.svg]]

An Emacs major mode for editing [[https://github.com/gfngfn/SATySFi][SATySFi]] documents.

SATySFi is a new typesetting system with a static type system. This package provides syntax highlighting, indentation support, and editing features for =.saty= and =.satyh= files.

* Features

- Syntax highlighting for SATySFi keywords, commands, and expressions
- Automatic file association for =.saty= and =.satyh= extensions
- Comment handling (=%=)
- SMIE-based indentation
- Support for row commands (=\command=), block commands (=+command=), and preprocessor directives

* Installation

** From MELPA

#+begin_src emacs-lisp
(use-package satysfi-mode
  :ensure t)
#+end_src

Or with =leaf=:

#+begin_src emacs-lisp
(leaf satysfi-mode :ensure t)
#+end_src

** Manual Installation

Clone this repository and add it to your load path:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/satysfi-mode.el")
(require 'satysfi-mode)
#+end_src

* Usage

The mode activates automatically when you open a file with =.saty= or =.satyh= extension.

* Requirements

- Emacs 26.1 or later

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

** Development Setup

Install [[https://github.com/cask/cask][Cask]] for dependency management:

#+begin_src shell
# macOS
brew install cask

# Manual installation
git clone https://github.com/cask/cask ~/.cask
export PATH="$HOME/.cask/bin:$PATH"
#+end_src

** Running Tests

#+begin_src shell
make test
#+end_src

* License

GPLv3. See [[https://github.com/conao3/satysfi-mode.el/blob/master/LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
